# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [158]:
from scipy import stats 
import numpy as np
from scipy.stats             import ttest_1samp,ttest_ind, wilcoxon
from statsmodels.stats.power import ttest_power
import matplotlib.pyplot     as     plt

In [159]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [161]:
# At 5% lelvel of significance
Alpha=0.05
population_mean=0
t_statistic, p_value = ttest_1samp(GPU1,0)
print(t_statistic,p_value)
print('P value %1.3f' % p_value)
print('Value of P <',Alpha,'So the statistical decision is to reject the null hypothesis at 5% level of significance.')
print('So, GPU1 mean is not equal to zero')

34.056241516158195 7.228892044970457e-15
P value 0.000
Value of P < 0.05 So the statistical decision is to reject the null hypothesis at 5% level of significance.
So, GPU1 mean is not equal to zero


## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [162]:
t_statistic, p_value  =  stats.ttest_ind(GPU1,GPU2)
print(t_statistic,p_value)
print('P Value is %1.3f' % p_value)
print('Value of P <',Alpha,'So the statistical decision is to reject the null hypothesis at 5% level of significance.')
print('So, there is a significant difference between datasets')

-2.627629513471839 0.013794282041452725
P Value is 0.014
Value of P < 0.05 So the statistical decision is to reject the null hypothesis at 5% level of significance.
So, there is a significant difference between datasets


## Question 3

He is trying a third GPU - GPU3.

In [0]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [0]:
#Null Hypothesis: There is no significant difference bewteen GPU1 and GPU3 speeds
#Alternate Hypothesis: There is a significant difference between GPU1 and GPU3 speeds
Alpha=0.05
t_statistic, p_value  =  stats.ttest_ind(GPU1,GPU3)
print(t_statistic,p_value)
print('P value is %1.3f' % p_value)
print('Value of P-',p_value, '>',Alpha,'So the statistical decision is NOT to reject the null hypothesis at 5% level of significance.')
print('There is no significant difference between the speeds of two GPUs i.e. GPU1 and GPU3')

## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [0]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [164]:
statistic, p_value=stats.levene(e1,e2,e3)
print(statistic,p_value)
print('P value is %1.3f' % p_value)
print('P value >', 0.05,'statistical decision is not to reject null hypothesis')
print('Since all input samples are from populations with equal variances, we can go ahead with ANOVA test')

2.6741725711150446 0.12259792666001798
P value is 0.123
P value > 0.05 statistical decision is not to reject null hypothesis
Since all input samples are from populations with equal variances, we can go ahead with ANOVA test


## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [166]:
#Null Hypothesis: Two or more groups have the same population mean
#Alternate Hypothesis: Two or more groups have mean not same as population mean
f_statistic, p_value=stats.f_oneway(e1,e2,e3)
print(f_statistic,p_value)
print('P value is %1.3f' % p_value)
print('Value of P >',Alpha,'So the statistical decision is NOT to reject the null hypothesis at 5% level of significance.')
print('Therefore, two or more groups have the same population mean')

2.51357622845924 0.13574644501798466
P value is 0.136
Value of P > 0.05 So the statistical decision is NOT to reject the null hypothesis at 5% level of significance.
Therefore, two or more groups have the same population mean


## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

In statistical hypothesis testing a type I error is the rejection of a true null hypothesis (also known as a 
"false positive" finding or conclusion) which is denoted by alpha
, while a type II error is the non-rejection of a false null hypothesis 
(also known as a "false negative" finding or conclusion) which is denoted by beta.

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


At 5% level of significance, is there any evidence in testing that waiting time for placing an order is 4.5 minutes.
Null Hypothesis:Waiting time to place an order in the past month is same as its previous population mean  
Alternate Hypothesis:Waiting time to place an order in the past month is not same as ts previous population mean
H0: 𝜇1 = 𝜇 
Ha: 𝜇1 ≠ 𝜇   
𝜇 = 4.5 minutes -previous population mean
𝜇1=mean of waiting time to place an order in the past month.

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [0]:
import numpy as np

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [0]:
import pandas as pd
from scipy import stats
alpha=0.01
Chi2_stat, p_value, degreeoffreedom, contingency=stats.chi2_contingency(dice)
print('Chi2 stat:',Chi2_stat)
print('P value:',p_value)
print('Since P value >',alpha,'statistical decision is not to reject null hypothesis')
print('Degree of Freedom:',degreeoffreedom)
print('Contingency Table:\n', contingency)

## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [167]:
Zscore=stats.zscore(dice)
P_value=stats.norm.sf(abs(Zscore))
P_mean=P_value.mean()
print('Zscore values:\n',Zscore)
print('P values:\n',P_value)
print('Mean of P values:',P_mean)

Zscore values:
 [[-0.46291005 -0.18884739 -1.83711731  1.44115338]
 [ 1.38873015 -0.64208114  1.22474487  0.        ]
 [ 0.9258201   0.7176201   0.61237244 -1.44115338]
 [-0.9258201   1.62408759  0.61237244 -0.96076892]
 [-1.38873015  0.03776948  0.          0.        ]
 [ 0.46291005 -1.54854863 -0.61237244  0.96076892]]
P values:
 [[0.32171442 0.42510621 0.03309629 0.07477068]
 [0.08245741 0.26041025 0.11033568 0.5       ]
 [0.17726974 0.23649578 0.27014569 0.07477068]
 [0.17726974 0.05217856 0.27014569 0.16833418]
 [0.08245741 0.48493574 0.5        0.5       ]
 [0.32171442 0.06074513 0.27014569 0.16833418]]
Mean of P values: 0.23428473233691496


## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [0]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [168]:
#Null Hypothesis: There is significant weight loss difference in patients before and after treatment
#Alternate Hypothesis: There is no significant weight loss difference in patients before and after treatment
alpha=0.05
t_statistic, p_value=stats.ttest_rel(before, after)
print(t_statistic,p_value)
print('P value is %1.3f' % p_value)
print('Value of P <',Alpha,'So the statistical decision is to reject the null hypothesis at 5% level of significance.')
print('So, there is no significant weight loss difference in patients after treatment')

6.204799633265735 1.1515813437971923e-09
P value is 0.000
Value of P < 0.05 So the statistical decision is to reject the null hypothesis at 5% level of significance.
So, there is no significant weight loss difference in patients after treatment
